name: Merge AdGuard Rules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # 或更新的版本

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install requests

      - name: Download Official Rules
        run: |
          python .github/scripts/download_rules.py --type official

      - name: Download Third-Party Rules
        run: |
          python .github/scripts/download_rules.py --type third_party

      - name: Merge And Deduplicate
        run: |
          # 合并自定义第三方规则
          cat ziyongdnsZ > ziyongdnsZ_temp
          cat ziyongrulerZ > ziyongrulerZ_temp
          #AdguardDNS_temp
          cat AdguardDNSRuler >> ziyongdnsZ_temp
          cat AdguardRuler >> ziyongrulerZ_temp

          # 清理重复并保存
          sort -u ziyongdnsZ_temp > ziyongdnsZ1
          sort -u ziyongrulerZ_temp > ziyongrulerZ1
          rm ziyongdnsZ_temp ziyongrulerZ_temp

      - name: Install HostlistCompiler (npm)
        run: npm install -g @adguard/hostlist-compiler

      - name: Optimize DNS rules
        run: |
          hostlist-compiler -i ziyongdnsZ1 -o ziyongdnsZ

      - name: Optimize General rules
        run: |
      #    hostlist-compiler -i ziyongrulerZ1 -o ziyongrulerZ
          cp ziyongrulerZ1 ziyongrulerZ

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ziyongdnsZ ziyongrulerZ ziyongrulerZ1 ziyongdnsZ1
          git commit -m "Updated AdGuard rules" || echo "No changes to commit"
          git push origin HEAD:main
